import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { services, getService } from '@/lib/services';

export function generateStaticParams() { return services.map((s) => ({ slug: s.slug })); }

const data = {
  en: {
    title: 'Live-in Maid Services in UAE', meta: 'Premium live-in maid services in UAE for families who need reliable full-time domestic help, cleaning, laundry, household support and documented hiring guidance.', badge: 'Premium Live-in Maid Hiring', lead: 'Hire a live-in maid in UAE through a clear, respectful and well-documented process designed for busy families, villas, apartments and households that need dependable daily support.', book: 'Book Consultation', whatsapp: 'WhatsApp Inquiry',
    whatTitle: 'What is a Live-in Maid Service?', whatText: 'A live-in maid is full-time domestic support who stays in the employer household and helps with day-to-day home management. INAYA supports families by understanding requirements, explaining options, coordinating documentation and guiding the hiring journey with privacy, clarity and professional follow-up.', whyTitle: 'Why Families Choose INAYA', includedTitle: 'Services Included', perfectTitle: 'Perfect For', journeyTitle: 'Live-in Maid Hiring Journey', journeyText: 'From first inquiry to home placement, every step is explained clearly so families understand requirements, documents and support before making a decision.', vettingTitle: 'INAYA Vetting Matrix', vettingText: 'Every recommendation is supported by a structured review process designed to protect the household, clarify expectations and improve long-term suitability.', countriesTitle: 'Countries We Source From', countriesText: 'INAYA works with experienced domestic worker profiles from key source markets, matched by language, household experience, cooking style, childcare exposure and family requirements.', pricingTitle: 'Transparent Pricing Guidance', pricingText: 'Every household is different, so final pricing depends on service type, duration, documentation, visa status and family requirements. We explain all costs before confirmation.', faqTitle: 'Live-in Maid FAQs', relatedTitle: 'Related Domestic Worker Services', finalTitle: 'Ready to hire a live-in maid?', finalText: 'Speak with INAYA today and get clear guidance for your family, documents and service plan.',
    cards: ['Full-time household support|Ideal for families who need reliable help throughout the week with cleaning, laundry and home routines.', 'Clear hiring guidance|We explain the service options, expected duties, documentation and next steps before confirmation.', 'Premium family experience|Communication stays private, organized and focused on what your home actually needs.'],
    why: ['Licensed UAE process guidance', 'Verified documentation support', 'Dedicated family coordinator', 'Clear replacement support policy', 'Privacy-first communication', 'Fast consultation and follow-up'],
    included: ['Daily cleaning and room care', 'Laundry and ironing support', 'Kitchen assistance and meal prep', 'Childcare support where suitable', 'Elderly household assistance', 'Pet-friendly home support', 'Villa and apartment routines', 'Organized daily task planning'],
    perfect: ['Working families', 'Large villas', 'New parents', 'Elderly households', 'Busy professionals', 'Families needing consistent help'],
    journey: ['Share Requirement|Tell us your emirate, household size, duties, language preference, live-in room arrangement and preferred start date.', 'Consultation Call|Our coordinator explains suitable hiring options, expected timelines, service scope and key documents.', 'Profile Matching|We shortlist suitable domestic workers based on home routine, experience, skills and family expectations.', 'Family Interview|You can review the match, ask questions and confirm comfort before moving to documentation.', 'Document Review|Identity details, passport information, eligibility and required paperwork are reviewed for the next step.', 'Agreement & Booking|Service terms, fees, replacement policy and responsibilities are clarified before confirmation.', 'Visa / Joining Coordination|Where applicable, coordination support is provided for visa, travel, medical and joining requirements.', 'Aftercare Support|INAYA remains available for family support, feedback, follow-up and replacement guidance as per policy.'],
    vetting: ['Identity Review|Passport, identity details and basic eligibility are checked before moving forward.', 'Skills Mapping|Cleaning, laundry, cooking, childcare and family routine requirements are matched carefully.', 'Behaviour Fit|Communication style, attitude and household suitability are considered during the review.', 'Experience Check|Available past household experience and practical strengths are reviewed for relevance.', 'Family Matching|Final recommendations are aligned with home size, emirate, timing and expectations.'],
    countries: ['Philippines|English communication, childcare, housekeeping', 'Indonesia|Housekeeping, cooking support, family care', 'Nepal|Reliable domestic support and cleaning routines', 'Sri Lanka|Experienced household help and meal support', 'India|Cooking, cleaning and family assistance', 'Kenya / Uganda|Housekeeping, childcare exposure and home support'],
    pricing: ['Consultation|Best for families comparing live-in maid options and requirements.|Requirement review|Document guidance|Service scope clarity', 'Live-in Placement|For families ready to proceed with candidate matching and booking.|Profile matching|Interview coordination|Joining support', 'Visa Support Guidance|For families who need help understanding documents, renewal or sponsorship steps.|Document checklist|Process guidance|Follow-up support'],
    faqs: ['How do I hire a live-in maid in UAE?|You can start by sharing your household needs, emirate, preferred duties and start date. INAYA then explains suitable options, required documents and next steps.', 'Can a live-in maid help with cleaning and laundry?|Yes, most live-in maid arrangements include daily cleaning, room care, laundry, ironing and general household support depending on the agreed scope.', 'Can I request childcare experience?|Yes, you can request childcare exposure, language preference and family routine experience during the consultation.', 'Is pricing fixed for every family?|No. Final cost depends on service model, documentation, visa status, duration and family requirements. We explain costs before confirmation.', 'Do you provide replacement support?|Replacement support depends on the selected package and policy. INAYA explains this clearly before booking.', 'Do you support Arabic families and expat families?|Yes, INAYA supports UAE national families, Arab families and expat households across the UAE.', 'Can I interview the candidate?|Where applicable, family interview or profile review is arranged before final confirmation.', 'Which emirates do you serve?|We support families across UAE subject to availability, documentation and service requirements.', 'What documents are required?|Documents vary by service type and visa status. Our coordinator provides a clear checklist during consultation.', 'How fast can a maid join?|Joining timelines depend on candidate availability, document status, visa process and family confirmation.'],
    related: ['live-out-maid', 'full-time-maid', 'part-time-maid', 'monthly-maid-contract', 'nanny', 'maid-visa', 'maid-replacement']
  },
  ar: {
    title: 'خدمات الخادمات المقيمات في الإمارات', meta: 'خدمات خادمات مقيمات في الإمارات للأسر التي تحتاج إلى مساعدة منزلية بدوام كامل مع تنظيف وغسيل ودعم منزلي وإرشاد واضح للتوظيف.', badge: 'توظيف خادمة مقيمة بشكل منظم', lead: 'استعن بخادمة مقيمة في الإمارات من خلال عملية واضحة ومحترمة ومنظمة تناسب الأسر المشغولة والفلل والشقق والمنازل التي تحتاج إلى دعم يومي موثوق.', book: 'احجز استشارة', whatsapp: 'استفسار واتساب',
    whatTitle: 'ما هي خدمة الخادمة المقيمة؟', whatText: 'الخادمة المقيمة هي دعم منزلي بدوام كامل تقيم في منزل صاحب العمل وتساعد في إدارة المهام اليومية. تدعم عناية الأسر من خلال فهم الاحتياجات، شرح الخيارات، تنسيق المستندات، وتوجيه رحلة التوظيف بخصوصية ووضوح ومتابعة احترافية.', whyTitle: 'لماذا تختار الأسر عناية؟', includedTitle: 'الخدمات المشمولة', perfectTitle: 'مناسبة لـ', journeyTitle: 'رحلة توظيف الخادمة المقيمة', journeyText: 'من أول استفسار حتى بدء الخدمة في المنزل، يتم شرح كل خطوة بوضوح حتى تفهم الأسرة المتطلبات والمستندات والدعم قبل اتخاذ القرار.', vettingTitle: 'مصفوفة التحقق في عناية', vettingText: 'كل ترشيح يعتمد على مراجعة منظمة تساعد على حماية الأسرة، توضيح التوقعات، وتحسين الملاءمة على المدى الطويل.', countriesTitle: 'الدول التي نوفر منها العمالة', countriesText: 'تعمل عناية مع ملفات عمالة منزلية من أسواق متعددة ويتم اختيارها حسب اللغة والخبرة المنزلية ونمط الطبخ ورعاية الأطفال واحتياج الأسرة.', pricingTitle: 'إرشاد واضح للأسعار', pricingText: 'كل منزل له احتياج مختلف، لذلك تعتمد التكلفة النهائية على نوع الخدمة والمدة والمستندات وحالة التأشيرة ومتطلبات الأسرة. نوضح جميع التفاصيل قبل التأكيد.', faqTitle: 'أسئلة شائعة عن الخادمة المقيمة', relatedTitle: 'خدمات منزلية ذات صلة', finalTitle: 'هل أنت جاهز لتوظيف خادمة مقيمة؟', finalText: 'تواصل مع عناية اليوم للحصول على إرشاد واضح لأسرتك والمستندات وخطة الخدمة.',
    cards: ['دعم منزلي بدوام كامل|مناسب للأسر التي تحتاج إلى مساعدة موثوقة طوال الأسبوع في التنظيف والغسيل وروتين المنزل.', 'إرشاد واضح للتوظيف|نشرح خيارات الخدمة والمهام المتوقعة والمستندات والخطوات التالية قبل التأكيد.', 'تجربة أسرية مميزة|يبقى التواصل خاصاً ومنظماً ومركزاً على ما يحتاجه منزلك فعلاً.'],
    why: ['إرشاد لعملية مرخصة في الإمارات', 'دعم التحقق من المستندات', 'منسق مخصص للأسرة', 'سياسة دعم للاستبدال بوضوح', 'تواصل يحافظ على الخصوصية', 'استشارة ومتابعة سريعة'],
    included: ['تنظيف يومي وترتيب الغرف', 'غسيل وكي الملابس', 'مساعدة في المطبخ والتحضير', 'دعم رعاية الأطفال عند المناسبة', 'مساعدة منزلية لكبار السن', 'دعم للمنازل التي لديها حيوانات أليفة', 'روتين للفلل والشقق', 'تنظيم المهام اليومية'],
    perfect: ['الأسر العاملة', 'الفلل الكبيرة', 'الآباء الجدد', 'منازل كبار السن', 'المهنيون المشغولون', 'الأسر التي تحتاج دعماً ثابتاً'],
    journey: ['شارك الاحتياج|أخبرنا بالإمارة، حجم الأسرة، المهام المطلوبة، اللغة المفضلة، ترتيب السكن وتاريخ البدء المناسب.', 'استشارة أولية|يشرح المنسق الخيارات المناسبة والمدة المتوقعة ونطاق الخدمة والمستندات الأساسية.', 'مطابقة الملف|نرشح خيارات مناسبة حسب روتين المنزل والخبرة والمهارات وتوقعات الأسرة.', 'مقابلة الأسرة|يمكن للأسرة مراجعة الترشيح وطرح الأسئلة والتأكد من الملاءمة قبل المستندات.', 'مراجعة المستندات|تتم مراجعة الهوية وجواز السفر والأهلية والأوراق المطلوبة للمرحلة التالية.', 'الاتفاق والحجز|يتم توضيح الشروط والرسوم وسياسة الاستبدال والمسؤوليات قبل التأكيد.', 'تنسيق التأشيرة والبدء|عند الحاجة، يتم دعم تنسيق التأشيرة والسفر والفحص الطبي ومتطلبات الالتحاق.', 'دعم ما بعد البدء|تبقى عناية متاحة للدعم والمتابعة والملاحظات وإرشاد الاستبدال حسب السياسة.'],
    vetting: ['مراجعة الهوية|يتم التحقق من جواز السفر وتفاصيل الهوية والأهلية الأساسية قبل المتابعة.', 'مطابقة المهارات|تتم مطابقة التنظيف والغسيل والطبخ ورعاية الأطفال وروتين الأسرة بعناية.', 'الملاءمة السلوكية|يتم أخذ أسلوب التواصل والالتزام والملاءمة المنزلية بعين الاعتبار.', 'مراجعة الخبرة|تتم مراجعة الخبرات المنزلية المتاحة ونقاط القوة العملية حسب الحاجة.', 'مطابقة الأسرة|تتم مواءمة الترشيح النهائي مع حجم المنزل والإمارة والتوقيت والتوقعات.'],
    countries: ['الفلبين|تواصل إنجليزي، رعاية أطفال، وتنظيم المنزل', 'إندونيسيا|تنظيف منزلي، دعم الطبخ، ورعاية الأسرة', 'نيبال|دعم منزلي موثوق وروتين تنظيف منتظم', 'سريلانكا|خبرة منزلية ودعم في الوجبات', 'الهند|طبخ وتنظيف ومساعدة أسرية', 'كينيا / أوغندا|تنظيف ورعاية أطفال ودعم منزلي'],
    pricing: ['استشارة|مناسبة للأسر التي تقارن خيارات الخادمة المقيمة والمتطلبات.|مراجعة الاحتياج|إرشاد المستندات|توضيح نطاق الخدمة', 'توظيف خادمة مقيمة|للأسر الجاهزة للمطابقة والحجز.|مطابقة الملفات|تنسيق المقابلة|دعم الالتحاق', 'إرشاد التأشيرة|للأسر التي تحتاج فهم المستندات أو التجديد أو نقل الكفالة.|قائمة مستندات|إرشاد العملية|متابعة الدعم'],
    faqs: ['كيف أوظف خادمة مقيمة في الإمارات؟|ابدأ بمشاركة احتياج المنزل والإمارة والمهام وتاريخ البدء. تقوم عناية بشرح الخيارات والمستندات والخطوات التالية.', 'هل تساعد الخادمة المقيمة في التنظيف والغسيل؟|نعم، غالباً تشمل الخدمة التنظيف اليومي وترتيب الغرف والغسيل والكي والدعم المنزلي حسب النطاق المتفق عليه.', 'هل يمكن طلب خبرة في رعاية الأطفال؟|نعم، يمكن طلب خبرة في رعاية الأطفال واللغة المناسبة وروتين الأسرة أثناء الاستشارة.', 'هل السعر ثابت لكل أسرة؟|لا. التكلفة النهائية تعتمد على نوع الخدمة والمستندات وحالة التأشيرة والمدة ومتطلبات الأسرة.', 'هل يوجد دعم للاستبدال؟|يعتمد دعم الاستبدال على الباقة والسياسة المختارة، ويتم توضيح ذلك قبل الحجز.', 'هل تخدمون الأسر العربية والوافدة؟|نعم، تدعم عناية الأسر الإماراتية والعربية والوافدة في الإمارات.', 'هل يمكن مقابلة المرشحة؟|عند الإمكانية، يتم ترتيب مراجعة الملف أو المقابلة قبل التأكيد النهائي.', 'ما الإمارات التي تخدمونها؟|نخدم الأسر داخل الإمارات حسب التوفر والمتطلبات والمستندات.', 'ما المستندات المطلوبة؟|تختلف المستندات حسب نوع الخدمة وحالة التأشيرة، ويقدم المنسق قائمة واضحة.', 'كم تستغرق مدة الالتحاق؟|تعتمد المدة على التوفر والمستندات والتأشيرة وتأكيد الأسرة.'],
    related: ['live-out-maid', 'full-time-maid', 'part-time-maid', 'monthly-maid-contract', 'nanny', 'maid-visa', 'maid-replacement']
  }
};

export async function generateMetadata({ params: { locale, slug } }: { params: { locale: string; slug: string } }): Promise<Metadata> { const s = getService(slug); if (!s) return {}; const l = locale === 'ar' ? 'ar' : 'en'; return { title: slug === 'live-in-maid' ? data[l].title : s.name[l], description: slug === 'live-in-maid' ? data[l].meta : s.short[l] }; }
const split = (v: string) => { const [title, text, a, b, c] = v.split('|'); return { title, text, points: [a, b, c].filter(Boolean) }; };
function ImageBlock({ label }: { label: string }) { return <div aria-label={label} className="relative min-h-[320px] overflow-hidden rounded-[28px] border border-white/75 bg-[linear-gradient(135deg,#efe9de,#ffffff,#e7edf6)] shadow-[0_28px_85px_rgba(7,22,74,0.10)] ring-1 ring-accent-500/10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_28%_20%,rgba(191,164,106,0.22),transparent_16rem),radial-gradient(circle_at_78%_76%,rgba(7,22,74,0.10),transparent_18rem)]" /><div className="absolute inset-6 rounded-[22px] border border-white/75 bg-white/20 backdrop-blur-sm" /><div className="absolute inset-x-10 bottom-10 h-px bg-gradient-to-r from-transparent via-accent-500 to-transparent" /></div>; }

export default async function ServiceDetailPage({ params: { locale, slug } }: { params: { locale: string; slug: string } }) {
  const s = getService(slug); if (!s) notFound(); const isArabic = locale === 'ar'; const l = isArabic ? 'ar' : 'en'; const copy = slug === 'live-in-maid' ? data[l] : null;
  if (!copy) return <div className="bg-ivory py-20 text-center"><h1 className="font-heading text-5xl font-bold text-primary-900">{s.name[l]}</h1><p className="mx-auto mt-5 max-w-2xl text-ink/70">{s.description[l]}</p><Link href={`/${locale}/booking`} className="btn-primary mt-8">{isArabic ? 'احجز الخدمة' : 'Book This Service'}</Link></div>;
  const heading = `${isArabic ? 'font-arabic' : 'font-heading'} text-3xl font-bold tracking-[-0.04em] text-primary-900 sm:text-5xl`;
  return <div className="overflow-hidden bg-[linear-gradient(180deg,#fbfaf7,#f8f6f0_48%,#ffffff)] text-ink">
    <section className="relative px-6 py-20 lg:px-10 lg:py-28"><div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_18%,rgba(191,164,106,0.18),transparent_28rem),radial-gradient(circle_at_10%_50%,rgba(7,22,74,0.08),transparent_26rem)]" /><div className="relative mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_0.85fr] lg:items-center"><div><span className="inline-flex rounded-full border border-accent-500/25 bg-white/70 px-5 py-2 text-xs font-bold uppercase tracking-[0.22em] text-accent-700">{copy.badge}</span><h1 className={`${isArabic ? 'font-arabic leading-[1.28]' : 'font-heading leading-[1.03]'} mt-7 text-[2.7rem] font-bold tracking-[-0.055em] text-primary-900 sm:text-[4.5rem]`}>{copy.title}</h1><p className="mt-6 max-w-2xl text-lg leading-9 text-ink/68">{copy.lead}</p><div className="mt-9 flex flex-col gap-4 sm:flex-row"><Link href={`/${locale}/booking?service=${slug}`} className="rounded-full bg-primary-900 px-8 py-4 text-center text-sm font-bold uppercase tracking-[0.14em] text-white shadow-[0_18px_45px_rgba(7,22,74,0.16)]">{copy.book}</Link><Link href={`/${locale}/contact`} className="rounded-full border border-accent-500/35 bg-white/60 px-8 py-4 text-center text-sm font-bold uppercase tracking-[0.14em] text-primary-900 shadow-[0_14px_35px_rgba(7,22,74,0.06)]">{copy.whatsapp}</Link></div></div><ImageBlock label="Live-in maid service hero image" /></div></section>
    <section className="px-6 py-16 lg:px-10"><div className="mx-auto grid max-w-7xl gap-5 md:grid-cols-3">{copy.cards.map((x) => { const c = split(x); return <div key={c.title} className="rounded-[28px] border border-white/75 bg-white/62 p-7 shadow-[0_24px_75px_rgba(7,22,74,0.075)] ring-1 ring-accent-500/10 backdrop-blur-2xl"><div className="mb-6 flex h-12 w-12 items-center justify-center rounded-full bg-accent-500/14 text-accent-700">✓</div><h2 className="font-heading text-2xl font-bold text-primary-900">{c.title}</h2><p className="mt-4 text-sm leading-7 text-ink/64">{c.text}</p></div>; })}</div></section>
    <section className="px-6 py-18 lg:px-10 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.9fr_1fr] lg:items-center"><ImageBlock label="Live-in maid duties image" /><div className="rounded-[30px] border border-white/75 bg-white/54 p-8 shadow-[0_28px_90px_rgba(7,22,74,0.08)]"><h2 className={heading}>{copy.whatTitle}</h2><p className="mt-6 text-base leading-9 text-ink/68">{copy.whatText}</p></div></div></section>
    <section className="px-6 py-16 lg:px-10 lg:py-24"><div className="mx-auto max-w-7xl"><SectionTitle title={copy.whyTitle} className={heading}/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{copy.why.map((x) => <Mini key={x} text={x}/>)}</div></div></section>
    <section className="px-6 py-16 lg:px-10 lg:py-24"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-2"><ListBox title={copy.includedTitle} items={copy.included} heading={heading}/><ListBox title={copy.perfectTitle} items={copy.perfect} heading={heading}/></div></section>
    <section className="px-6 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-7xl"><SectionTitle title={copy.journeyTitle} text={copy.journeyText} className={heading}/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{copy.journey.map((x,i)=>{const c=split(x);return <Step key={c.title} n={i+1} title={c.title} text={c.text}/>})}</div></div></section>
    <section className="px-6 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-7xl rounded-[34px] border border-white/75 bg-white/50 p-8 shadow-[0_30px_95px_rgba(7,22,74,0.08)] lg:p-12"><SectionTitle title={copy.vettingTitle} text={copy.vettingText} className={heading}/><div className="grid gap-4 md:grid-cols-5">{copy.vetting.map((x,i)=>{const c=split(x);return <Step key={c.title} n={i+1} title={c.title} text={c.text}/>})}</div></div></section>
    <section className="px-6 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-7xl"><SectionTitle title={copy.countriesTitle} text={copy.countriesText} className={heading}/><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{copy.countries.map((x)=>{const c=split(x);return <div key={c.title} className="rounded-[26px] border border-white/75 bg-white/58 p-6 shadow-[0_22px_70px_rgba(7,22,74,0.065)]"><div className="mb-5 h-32 rounded-[20px] border border-white/75 bg-[linear-gradient(135deg,#f2eadc,#ffffff,#e7edf6)]"/><h3 className="font-heading text-2xl font-bold text-primary-900">{c.title}</h3><p className="mt-3 text-sm leading-7 text-ink/62">{c.text}</p></div>})}</div></div></section>
    <section className="px-6 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-7xl"><SectionTitle title={copy.pricingTitle} text={copy.pricingText} className={heading}/><div className="grid gap-5 lg:grid-cols-3">{copy.pricing.map((x)=>{const c=split(x);return <div key={c.title} className="rounded-[30px] border border-white/75 bg-white/62 p-8 shadow-[0_26px_80px_rgba(7,22,74,0.075)] ring-1 ring-accent-500/10"><h3 className="font-heading text-2xl font-bold text-primary-900">{c.title}</h3><p className="mt-4 text-sm leading-7 text-ink/64">{c.text}</p><div className="mt-6 space-y-3">{c.points.map((p)=><Mini key={p} text={p}/>)}</div><Link href={`/${locale}/booking?service=${slug}`} className="mt-7 inline-flex rounded-full bg-primary-900 px-6 py-3 text-sm font-bold text-white">{copy.book}</Link></div>})}</div></div></section>
    <section className="px-6 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-5xl"><SectionTitle title={copy.faqTitle} className={heading}/><div className="space-y-4">{copy.faqs.map((x)=>{const c=split(x);return <details key={c.title} className="rounded-[22px] border border-white/75 bg-white/64 p-5 shadow-[0_18px_55px_rgba(7,22,74,0.055)]"><summary className="cursor-pointer font-heading text-lg font-bold text-primary-900">{c.title}</summary><p className="mt-4 text-sm leading-7 text-ink/64">{c.text}</p></details>})}</div></div></section>
    <section className="px-6 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-7xl"><SectionTitle title={copy.relatedTitle} className={heading}/><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{copy.related.map((r)=>{const rs=getService(r);return rs?<Link key={r} href={`/${locale}/services/${r}`} className="rounded-[24px] border border-white/75 bg-white/60 p-6 shadow-[0_20px_65px_rgba(7,22,74,0.065)]"><div className="text-3xl">{rs.icon}</div><h3 className="mt-5 font-heading text-xl font-bold text-primary-900">{rs.name[l]}</h3><p className="mt-3 text-sm leading-7 text-ink/62">{rs.short[l]}</p></Link>:null})}</div></div></section>
    <section className="px-6 pb-24 lg:px-10"><div className="mx-auto max-w-5xl rounded-[34px] border border-white/75 bg-white/65 p-10 text-center shadow-[0_30px_95px_rgba(7,22,74,0.09)]"><h2 className={heading}>{copy.finalTitle}</h2><p className="mx-auto mt-5 max-w-2xl text-base leading-8 text-ink/64">{copy.finalText}</p><Link href={`/${locale}/booking?service=${slug}`} className="mt-8 inline-flex rounded-full bg-primary-900 px-8 py-4 text-sm font-bold uppercase tracking-[0.14em] text-white">{copy.book}</Link></div></section>
  </div>;
}
function SectionTitle({title,text,className}:{title:string;text?:string;className:string}){return <div className="mb-12 text-center"><h2 className={className}>{title}</h2>{text&&<p className="mx-auto mt-5 max-w-3xl text-base leading-8 text-ink/64">{text}</p>}<div className="mx-auto mt-5 h-px w-24 bg-gradient-to-r from-transparent via-accent-500 to-transparent" /></div>}
function Mini({text}:{text:string}){return <div className="flex items-start gap-3 rounded-2xl border border-accent-500/12 bg-white/58 p-4 text-sm font-semibold text-ink/72"><span className="text-accent-700">✓</span><span>{text}</span></div>}
function ListBox({title,items,heading}:{title:string;items:string[];heading:string}){return <div className="rounded-[30px] border border-white/75 bg-white/58 p-8 shadow-[0_24px_75px_rgba(7,22,74,0.07)]"><h2 className={heading}>{title}</h2><div className="mt-7 grid gap-3 sm:grid-cols-2">{items.map((x)=><Mini key={x} text={x}/>)}</div></div>}
function Step({n,title,text}:{n:number;title:string;text:string}){return <div className="relative overflow-hidden rounded-[24px] border border-white/75 bg-white/62 p-6 shadow-[0_22px_70px_rgba(7,22,74,0.065)]"><span className="font-heading text-4xl font-bold text-accent-500/42">{String(n).padStart(2,'0')}</span><h3 className="mt-5 font-heading text-xl font-bold text-primary-900">{title}</h3><p className="mt-3 text-sm leading-7 text-ink/64">{text}</p></div>}
