type Localized = { en: string; ar: string };
export const guideContent: Record<string, { title: Localized; sections: { title: Localized; body: Localized; route: string }[] }> = {
  'service-guidelines': {
    title: { en: 'Prepare the service conversation', ar: 'استعد لمناقشة الخدمة' }, sections: [
      { title: { en: 'Define the role before comparing profiles', ar: 'حدد الدور قبل مقارنة الملفات' }, body: { en: 'List the main household tasks and identify the priority role. Cleaning, childcare and cooking are different responsibilities; explain which you need rather than assuming every duty belongs in one general maid request.', ar: 'حدد المهام المنزلية الأساسية والدور ذا الأولوية. التنظيف ورعاية الأطفال والطبخ مسؤوليات مختلفة؛ وضح ما تحتاجه بدلاً من افتراض شمول كل مهمة في طلب خادمة عام.' }, route: 'services' },
      { title: { en: 'Separate residence from the working pattern', ar: 'افصل الإقامة عن نمط العمل' }, body: { en: 'Live-in and live-out describe accommodation, while full-time, part-time and monthly requests describe other parts of the arrangement. Explain the home routine, preferred schedule and accommodation separately so the enquiry is clear.', ar: 'تصف الإقامة داخل المنزل أو خارجه السكن، بينما يصف الدوام الكامل والجزئي والطلب الشهري جوانب أخرى من الترتيب. وضح روتين المنزل والجدول والإقامة بشكل منفصل ليكون الطلب واضحاً.' }, route: 'how-it-works' },
      { title: { en: 'Review the case before confirmation', ar: 'راجع الحالة قبل التأكيد' }, body: { en: 'Gather the emirate, residential area, duties and current situation. The team reviews the applicable documents, scope and price before confirmation; the preparation guide is not a final legal checklist or proof of availability.', ar: 'جهز الإمارة والمنطقة السكنية والمهام والوضع الحالي. يراجع الفريق المستندات المناسبة والنطاق والسعر قبل التأكيد؛ ودليل الاستعداد ليس قائمة قانونية نهائية أو دليلاً على التوفر.' }, route: 'documents-required' }
    ]
  },
  'support-process': {
    title: { en: 'Make an existing-service review useful', ar: 'اجعل مراجعة الخدمة القائمة مفيدة' }, sections: [
      { title: { en: 'Describe the concern against the booked duties', ar: 'صف الملاحظة وفق المهام المحجوزة' }, body: { en: 'Share the booking and service details, then explain the concern in relation to the duties that were agreed. Separating an existing-service issue from a new request helps the team understand what needs review.', ar: 'شارك تفاصيل الحجز والخدمة ثم اشرح الملاحظة بالنسبة إلى المهام المتفق عليها. يساعد فصل مشكلة خدمة قائمة عن طلب جديد الفريق على فهم ما يحتاج مراجعة.' }, route: 'contact' },
      { title: { en: 'Use the confirmed agreement', ar: 'ارجع إلى الاتفاق المؤكد' }, body: { en: 'Keep the agreement terms and relevant timing clear during the review. Replacement or refund eligibility depends on the selected service and the confirmed terms; a general support enquiry does not establish an entitlement or outcome.', ar: 'وضح شروط الاتفاق والتوقيت المناسب أثناء المراجعة. تعتمد أهلية الاستبدال أو الاسترداد على الخدمة المختارة والشروط المؤكدة؛ ولا يثبت طلب الدعم العام حقاً أو نتيجة محددة.' }, route: 'refund-policy' },
      { title: { en: 'Clarify the next step rather than assume it', ar: 'وضح الخطوة التالية بدلاً من افتراضها' }, body: { en: 'After the case is reviewed, discuss the options applicable to the arrangement and current availability. Keep outstanding questions visible and confirm the next action with the team instead of treating this guide as a replacement commitment.', ar: 'بعد مراجعة الحالة، ناقش الخيارات المناسبة للترتيب والتوفر الحالي. أبق الأسئلة غير المحسومة واضحة وأكد الإجراء التالي مع الفريق بدلاً من اعتبار الدليل التزاماً بالاستبدال.' }, route: 'services/maid-replacement' }
    ]
  },
  blog: {
    title: { en: 'Guides you can use now', ar: 'أدلة يمكنك استخدامها الآن' }, sections: [
      { title: { en: 'Understand the enquiry process', ar: 'افهم خطوات الطلب' }, body: { en: 'Use the existing process guide to move from a household requirement to a service discussion. It explains what to share first and which details need review before confirmation.', ar: 'استخدم دليل العملية الحالي للانتقال من احتياج منزلي إلى مناقشة الخدمة. يوضح ما تشاركه أولاً والتفاصيل التي تحتاج مراجعة قبل التأكيد.' }, route: 'how-it-works' },
      { title: { en: 'Prepare the relevant information', ar: 'جهز المعلومات المناسبة' }, body: { en: 'The documents guide separates basic enquiry details from recruitment, visa and sponsorship preparation. Read it for your selected service path rather than assuming every request needs the same documents.', ar: 'يفصل دليل المستندات بيانات الطلب الأساسية عن الاستعداد للتوظيف والتأشيرة والكفالة. اقرأه لمسار خدمتك المختار بدلاً من افتراض حاجة كل طلب إلى المستندات نفسها.' }, route: 'documents-required' },
      { title: { en: 'Choose the right service questions', ar: 'اختر أسئلة الخدمة المناسبة' }, body: { en: 'The FAQ categories cover services, booking, pricing, support and procedures. Choose the relevant category, then ask the team about any point that depends on your individual household or existing agreement.', ar: 'تغطي فئات الأسئلة الخدمات والحجز والأسعار والدعم والإجراءات. اختر الفئة المناسبة ثم اسأل الفريق عن أي نقطة تعتمد على منزلك أو اتفاقك القائم.' }, route: 'faq' }
    ]
  }
};
