type Localized = { en: string; ar: string };
// No nationality-wide skills or availability assertions: these are profile-review prompts.
export const countryContentBriefs: Record<string, Localized> = {
  'philippines-maid-uae': { en: 'If the Philippines is your preference, separate communication needs from childcare and housekeeping duties. Ask about the individual’s language and previous tasks; nationality alone cannot establish either. Use the nanny guide when child supervision is the main role.', ar: 'إذا كنت تفضل الفلبين، فافصل احتياجات التواصل عن مهام رعاية الأطفال وأعمال المنزل. اسأل عن لغة الشخص ومهامه السابقة؛ فالجنسية وحدها لا تثبت أياً منهما. استخدم دليل المربية عندما يكون الإشراف على الطفل هو الدور الأساسي.' },
  'sri-lankan-maid-uae': { en: 'For a Sri Lanka preference, describe the everyday meals and cleaning routine you want to discuss. Review cooking experience and household duties separately on each profile, rather than treating a source country as evidence of either skill.', ar: 'عند تفضيل سريلانكا، وضح الوجبات اليومية وروتين التنظيف الذي تريد مناقشته. راجع خبرة الطبخ والمهام المنزلية لكل ملف بشكل منفصل، ولا تعتبر دولة المصدر دليلاً على امتلاك أي مهارة.' },
  'nepali-maid-uae': { en: 'A Nepal preference can be considered alongside a defined housekeeping role. Clarify whether you are discussing residence in the home, full-time work or scheduled tasks: those are different arrangements, and each must be checked against the individual profile and documents.', ar: 'يمكن مناقشة تفضيل نيبال مع دور محدد لأعمال المنزل. وضح هل تناقش الإقامة في المنزل أم الدوام الكامل أم مهاماً مجدولة؛ فهي ترتيبات مختلفة، ويجب مراجعة كل منها وفق الملف الفردي والمستندات.' },
  'indian-maid-uae': { en: 'When reviewing an India preference, name the languages you use at home and the cooking duties you need. Neither communication nor recipe experience should be assumed from nationality. Compare the cooking guide with the housemaid guide to define the role before requesting profiles.', ar: 'عند مراجعة تفضيل الهند، حدد اللغات المستخدمة في منزلك ومهام الطبخ المطلوبة. لا ينبغي افتراض اللغة أو الخبرة بالوصفات من الجنسية. قارن دليل الطبخ بدليل عاملة المنزل لتحديد الدور قبل طلب الملفات.' },
  'bangladeshi-maid-uae': { en: 'For a Bangladesh enquiry, distinguish cleaning and laundry from kitchen preparation. A clear task list helps you review relevant experience instead of asking one general profile to cover several undefined roles. Check the housekeeping and kitchen-helper guides for those different purposes.', ar: 'في طلب يتعلق ببنغلاديش، ميز التنظيف والغسيل عن التحضير في المطبخ. تساعد قائمة واضحة على مراجعة الخبرة المناسبة بدلاً من طلب عدة أدوار غير محددة من ملف عام. راجع دليلي التنظيف ومساعد المطبخ للغرضين المختلفين.' },
  'ethiopian-maid-uae': { en: 'An Ethiopia preference is a starting point for an individual review, not a description of care or cleaning ability. Explain the household duties first, then discuss communication, previous experience and document status before considering a working arrangement.', ar: 'تفضيل إثيوبيا نقطة بداية لمراجعة فردية، وليس وصفاً للقدرة على الرعاية أو التنظيف. وضح المهام المنزلية أولاً، ثم ناقش التواصل والخبرة السابقة وحالة المستندات قبل اختيار ترتيب العمل.' },
  'kenyan-maid-uae': { en: 'If you are comparing Kenya profiles for childcare and home support, decide which responsibility takes priority. Child supervision and cleaning have different expectations. Review the relevant experience on each profile and discuss the language needed for communication with your family.', ar: 'إذا كنت تقارن ملفات من كينيا لرعاية الأطفال ودعم المنزل، فحدد المسؤولية ذات الأولوية. للإشراف على الطفل والتنظيف توقعات مختلفة. راجع الخبرة المناسبة لكل ملف وناقش لغة التواصل المطلوبة مع الأسرة.' },
  'ugandan-maid-uae': { en: 'An Uganda enquiry should identify whether the main need is housekeeping, companionship or another household role. Use the service guides to separate these tasks before comparing profiles; a nationality preference does not define the scope of care or the candidate’s experience.', ar: 'ينبغي أن يوضح طلب أوغندا هل الحاجة الأساسية تنظيف المنزل أم المرافقة أم دوراً منزلياً آخر. استخدم أدلة الخدمات لفصل المهام قبل مقارنة الملفات؛ فتفضيل الجنسية لا يحدد نطاق الرعاية أو خبرة المرشحة.' },
  'ghanaian-maid-uae': { en: 'For a Ghana preference, begin with the family routine and the duties a profile would need to support. Compare candidates using the same experience and communication questions used for other source countries, keeping document status and unanswered questions visible before deciding.', ar: 'عند تفضيل غانا، ابدأ بروتين الأسرة والمهام التي يحتاج الملف إلى دعمها. قارن المرشحين بأسئلة الخبرة والتواصل نفسها المستخدمة للدول الأخرى، مع إبقاء حالة المستندات والأسئلة غير المحسومة واضحة قبل القرار.' },
  'sierra-leone-maid-uae': { en: 'A Sierra Leone enquiry can be organized around the household tasks, working arrangement and experience you want to review. Ask the team which individual profiles can be discussed for that request; this country guide is not a confirmation of stock, a start date or package eligibility.', ar: 'يمكن تنظيم طلب سيراليون حول المهام المنزلية وترتيب العمل والخبرة المطلوب مراجعتها. اسأل الفريق عن الملفات الفردية التي يمكن مناقشتها للطلب؛ فهذا الدليل لا يؤكد توفر مرشحات أو موعد بدء أو أهلية باقة.' },
  'indonesian-maid-uae': { en: 'For an Indonesia preference, separate routine housekeeping from cooking and family-care expectations. Describe the actual meals or tasks and review the individual’s experience with them. The service role and document review remain necessary even when a country preference is clear.', ar: 'عند تفضيل إندونيسيا، افصل أعمال المنزل المعتادة عن توقعات الطبخ ورعاية الأسرة. وضح الوجبات أو المهام الفعلية وراجع خبرة الشخص بها. يظل تحديد الدور ومراجعة المستندات ضرورياً حتى مع وضوح تفضيل الدولة.' },
  'myanmar-maid-uae': { en: 'When discussing Myanmar profiles, turn a broad request for home help into a cleaning checklist and a communication preference. Review those details with each individual profile. A source-country listing does not confirm current availability or that every candidate has the same background.', ar: 'عند مناقشة ملفات ميانمار، حول طلب المساعدة المنزلية العام إلى قائمة تنظيف وتفضيل للتواصل. راجع التفاصيل مع كل ملف فردي. إدراج دولة المصدر لا يؤكد التوفر الحالي أو تشابه خلفيات جميع المرشحين.' }
};

export const locationContentBriefs: Record<string, Localized> = {
  'maid-services-ajman': { en: 'For an Ajman enquiry, share the residential area and the household duties before choosing an arrangement. INAYA’s listed office is in Grand Mall, Ajman; contact the team before planning a visit. Office location does not by itself confirm worker availability in your neighbourhood.', ar: 'لطلب في عجمان، شارك المنطقة السكنية والمهام المنزلية قبل اختيار الترتيب. مكتب عناية المذكور في جراند مول بعجمان؛ تواصل مع الفريق قبل التخطيط للزيارة. موقع المكتب وحده لا يؤكد توفر عاملة في منطقتك.' },
  'maid-services-dubai': { en: 'In a Dubai enquiry, distinguish the home address from the work pattern: scheduled visits, a live-in arrangement and regular childcare are different requests. Share the area, access arrangements and priority duties so the team can review the actual household need rather than a city-wide assumption.', ar: 'في طلب دبي، ميز عنوان المنزل عن نمط العمل: فالزيارات المجدولة والإقامة في المنزل ورعاية الأطفال المنتظمة طلبات مختلفة. شارك المنطقة وترتيبات الدخول والمهام ذات الأولوية لمراجعة الاحتياج الفعلي بدلاً من افتراض عام عن المدينة.' },
  'maid-services-sharjah': { en: 'For Sharjah, describe the family timetable and separate cleaning from childcare or cooking responsibilities. Use the individual service guides to decide which role to discuss, then share the residential area and preferred arrangement for a case-specific availability review.', ar: 'لطلب الشارقة، وضح جدول الأسرة وافصل التنظيف عن مسؤوليات رعاية الأطفال أو الطبخ. استخدم أدلة الخدمات لتحديد الدور المطلوب، ثم شارك المنطقة السكنية والترتيب المفضل لمراجعة التوفر حسب الحالة.' },
  'maid-services-abu-dhabi': { en: 'For an Abu Dhabi home, start with the workload and household roles rather than assuming the size of the home determines the service. Explain recurring duties, childcare or care-support needs, and whether the enquiry is about recruitment, an existing arrangement or document guidance.', ar: 'لمنزل في أبوظبي، ابدأ بحجم العمل والأدوار المنزلية بدلاً من افتراض أن مساحة المنزل تحدد الخدمة. وضح المهام المتكررة واحتياجات الأطفال أو الرعاية وهل يخص الطلب التوظيف أم ترتيباً قائماً أم إرشاد المستندات.' },
  'maid-services-ras-al-khaimah': { en: 'For Ras Al Khaimah, provide the area and describe whether you need continuing daily help or particular scheduled tasks. Residence in the home and the amount of work are separate choices. Review both with the team before moving from a location enquiry to a confirmed service.', ar: 'لطلب رأس الخيمة، حدد المنطقة وهل تحتاج مساعدة يومية مستمرة أم مهاماً محددة مجدولة. الإقامة في المنزل وحجم العمل خياران منفصلان. راجعهما مع الفريق قبل الانتقال من استفسار المنطقة إلى خدمة مؤكدة.' },
  'maid-services-fujairah': { en: 'A Fujairah enquiry is clearer when cleaning, cooking and childcare tasks are listed separately. Share the household area and the role you want to review. The guides below explain those service purposes; the team checks the particular request before confirming an arrangement.', ar: 'يكون طلب الفجيرة أوضح عند فصل مهام التنظيف والطبخ ورعاية الأطفال. شارك منطقة المنزل والدور المطلوب مراجعته. توضح الأدلة أدناه أغراض الخدمات، ويراجع الفريق الطلب المحدد قبل تأكيد الترتيب.' },
  'maid-services-umm-al-quwain': { en: 'For Umm Al Quwain, use this page to choose the service conversation you need: a maid arrangement, childcare, cooking or care support. State the residential area and current situation. If the enquiry concerns recruitment or visa guidance, clarify that separately from the daily household duties.', ar: 'لطلب أم القيوين، استخدم الصفحة لتحديد نوع المناقشة: ترتيب خادمة أو رعاية أطفال أو طبخ أو دعم رعاية. حدد المنطقة السكنية والوضع الحالي. إذا كان الطلب يخص التوظيف أو التأشيرة، فوضحه بشكل منفصل عن المهام اليومية.' }
};
